### ISSUE TITLE
A plugin by the name "Omeka\Form\Element\Query" was not found in the plugin manager

### ISSUE THREAD

**Issue by Marcool04** [omeka-s-modules/FacetedBrowse#1]
Hi there,
I am working with a librarian colleague at a research library in France, setting up an Omeka-S website, and we wished to use your plugin, however we have run into a possible bug.
After cloning the repository into `/omeka-s-root/modules/FacetedBrowse`, I clicked on "Install" in the Omeka-S administrative interface module page, and the module appears to install ok (no error messages in Apache logs output nor on screen).
However, when I navigate to the Faceted Browse section of the site configuration, and attempt to add a category, this message is printed to screen:

````
 Laminas\Form\Exception\InvalidElementException
A plugin by the name "Omeka\Form\Element\Query" was not found in the plugin manager Laminas\Form\FormElementManager\FormElementManagerV3Polyfill

Détails :

Laminas\Form\Exception\InvalidElementException: A plugin by the name "Omeka\Form\Element\Query" was not found in the plugin manager Laminas\Form\FormElementManager\FormElementManagerV3Polyfill in /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerTrait.php:47
Stack trace:
#0 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-form/src/Factory.php(128): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->get('Omeka\\Form\\Elem...')
#1 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-form/src/Form.php(188): Laminas\Form\Factory->create(Array)
#2 /var/www/html/bibnum.asie-pacifique.fr/modules/FacetedBrowse/src/Form/CategoryForm.php(29): Laminas\Form\Form->add(Array)
#3 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerV3Polyfill.php(323): FacetedBrowse\Form\CategoryForm->init()
#4 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(780): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->callElementInit(Object(Laminas\ServiceManager\ServiceManager), Object(FacetedBrowse\Form\CategoryForm))
#5 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(228): Laminas\ServiceManager\ServiceManager->doCreate('FacetedBrowse\\F...', Array)
#6 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(153): Laminas\ServiceManager\ServiceManager->build('FacetedBrowse\\F...', Array)
#7 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerTrait.php(56): Laminas\ServiceManager\AbstractPluginManager->get('FacetedBrowse\\F...', Array, true)
#8 /var/www/html/bibnum.asie-pacifique.fr/application/src/Mvc/Controller/Plugin/GetForm.php(33): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->get('FacetedBrowse\\F...', Array)
#9 [internal function]: Omeka\Mvc\Controller\Plugin\GetForm->__invoke('FacetedBrowse\\F...', Array)
#10 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(275): call_user_func_array(Object(Omeka\Mvc\Controller\Plugin\GetForm), Array)
#11 /var/www/html/bibnum.asie-pacifique.fr/modules/FacetedBrowse/src/Controller/SiteAdmin/CategoryController.php(36): Laminas\Mvc\Controller\AbstractController->__call('getForm', Array)
#12 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): FacetedBrowse\Controller\SiteAdmin\CategoryController->addAction()
#13 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#14 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#15 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#16 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#17 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#18 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#19 /var/www/html/bibnum.asie-pacifique.fr/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#20 /var/www/html/bibnum.asie-pacifique.fr/index.php(21): Laminas\Mvc\Application->run()
#21 {main}
````

The line referenced is this one: https://github.com/omeka-s-modules/FacetedBrowse/blob/56c6fd297221a4c7bb768022e225966b31b695b4/src/Form/CategoryForm.php#L29

I see that particular class was added (by you actually :) ) to Omeka-S with this commit https://github.com/omeka/omeka-s/commit/3e2cb964f7ad248a7fe30e66c864113f6a028e5f a few months ago only, and I guess the problem here is I simply need to update my version of Omeka-S.
Maybe it would be worth including a minimum required version constraint on installation so that others with 
(slightly) outdated installations don't bump into this error.

Thanks for all your work on this anyhow!
Best regards,
Mark.

Other info:
- Omeka-S version: version 3.0.1
- PHP version: 
````
PHP 7.3.27-1~deb10u1 (cli) (built: Feb 13 2021 16:31:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
````

**Comment by adehner** [comment]
My colleague told me about development on this module. I'm pretty excited about it, and would be happy to help out as a guinea pig tester when you're ready for that. Do you have a rough idea about your beta release date?

**Comment by jimsafley** [comment]
I do not have a good sense on a release date. This module will only work on the development branch of Omeka S, so we have to wait until that's released, possibly within the next few weeks. In addition to that, we have to do internal testing and documentation prior to a release. Of course you're free to test the module now if you're willing to fork the Omeka S repository and use the `develop` branch.
