### ISSUE TITLE
Update causes error: "Base table or view not found 'map.faceted_browse_column'"

### ISSUE THREAD

**Issue by Marcool04** [omeka-s-modules/FacetedBrowse#43]
Hi there,

I am attempting to update from version 0.1.0 to 1.4.1 after also having recently updated to Omeka-S version 4.0.4 and I am getting the following error:

```
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'map.faceted_browse_column' doesn't exist in /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:55 Stack trace: 
#0 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(55): PDO->exec() 
#1 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1579): Doctrine\DBAL\Driver\PDOConnection->exec() 
#2 /var/www/html/omeka-s/modules/FacetedBrowse/Module.php(65): Doctrine\DBAL\Connection->exec() 
#3 /var/www/html/omeka-s/application/src/Module/Manager.php(307): FacetedBrowse\Module->upgrade() 
#4 /var/www/html/omeka-s/application/src/Controller/Admin/ModuleController.php(250): Omeka\Module\Manager->upgrade() 
#5 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ModuleController->upgradeAction() 
#6 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch() 
#7 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners() 
#8 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil() 
#9 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch() 
#10 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch() 
#11 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners() 
#12 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil() 
#13 /var/www/html/omeka-s/index.php(21): Laminas\Mvc\Application->run() 
#14 {main} Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'map.faceted_browse_column' doesn't exist in /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18 Stack trace: 
#0 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(60): Doctrine\DBAL\Driver\PDO\Exception::new() 
#1 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1579): Doctrine\DBAL\Driver\PDOConnection->exec() 
#2 /var/www/html/omeka-s/modules/FacetedBrowse/Module.php(65): Doctrine\DBAL\Connection->exec() 
#3 /var/www/html/omeka-s/application/src/Module/Manager.php(307): FacetedBrowse\Module->upgrade() 
#4 /var/www/html/omeka-s/application/src/Controller/Admin/ModuleController.php(250): Omeka\Module\Manager->upgrade() 
#5 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ModuleController->upgradeAction() 
#6 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch() 
#7 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners() 
#8 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil() 
#9 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch() 
#10 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch() 
#11 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners() 
#12 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil() 
#13 /var/www/html/omeka-s/index.php(21): Laminas\Mvc\Application->run() 
#14 {main} Next Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'ALTER TABLE faceted_browse_column ADD exclude_sort_by TINYINT(1) NOT NULL AFTER type': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'map.faceted_browse_column' doesn't exist in /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:61 Stack trace: 
#0 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException() 
#1 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\DBAL\DBALException::wrapException() 
#2 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2226): Doctrine\DBAL\DBALException::driverExceptionDuringQuery() 
#3 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1581): Doctrine\DBAL\Connection->handleExceptionDuringQuery() 
#4 /var/www/html/omeka-s/modules/FacetedBrowse/Module.php(65): Doctrine\DBAL\Connection->exec() 
#5 /var/www/html/omeka-s/application/src/Module/Manager.php(307): FacetedBrowse\Module->upgrade() 
#6 /var/www/html/omeka-s/application/src/Controller/Admin/ModuleController.php(250): Omeka\Module\Manager->upgrade() 
#7 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ModuleController->upgradeAction() 
#8 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch() 
#9 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners() 
#10 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil() 
#11 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch() 
#12 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch() 
#13 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners() 
#14 /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil() 
#15 /var/www/html/omeka-s/index.php(21): Laminas\Mvc\Application->run() 
#16 {main}
```

More information about the system itself:

```
# php --version
PHP 7.4.33 (cli) (built: Sep  4 2023 08:15:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
[SNIP]

# apachectl -v
Server version: Apache/2.4.38 (Debian)
Server built:   2023-04-21T22:01:00

# mariadb --version
mariadb  Ver 15.1 Distrib 10.3.39-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

Maybe it was too much of a leap to go from 0.1.0 to this later version in one go? Is there anything I can do now to get out of the "stuck" situation where I can't upgrade the module?

Do let me know if you need me to do any more debugging.

Thanks in advance for your help.
Regards,
Mark.

**Comment by jimsafley** [comment]
It looks like you installed an early development version (0.1.0), which is not published on the [module's page](https://omeka.org/s/modules/FacetedBrowse/), and does not have a guaranteed migration path. You could try fixing the database by hand as errors occur (it's almost certainly the first of several database errors), but it'll require some technical know-how and digging through the commits to find the correct `ALTER` and `CREATE` statements.

I would ask if you made a database backup, but you'd be in the same predicament even if you had. It's likely that your only path forward is to uninstall the module, install the most recent version, and rebuild your faceted browse pages.

**Comment by Marcool04** [comment]
Hi Jim,
Thanks for taking the time to explain. I realise the steep update path from a long out of date module was a bad idea... Should have just uninstalled and reinstalled but I didn't notice how far out of date we were.
I'll see what the best way forward is. Actually I'm not sure the users are doing anything with faceted browse any more (I need to check that). Would it be possible for me to just delete the Module from the filesystem, and let the database elements sit there? Or is there an uninstall script somewhere in the 0.1.0 version which I could run to clean out the database entirely?
Thanks for any pointers.
Regards,
Mark.

**Comment by jimsafley** [comment]
It should be fine to delete the FacetedBrowse directory, though the module would still show an error on the modules page. To fix this, you'll need to delete the module from the database using `DELETE FROM modules WHERE id = 'FacetedBrowse'`. Once you're in the database, you could go ahead and delete the remaining tables.

**Comment by Marcool04** [comment]
Thanks that's very helpful of you.
Cheers.

**Comment by Marcool04** [comment]
PS: seems to have worked fine. I just did:

```sql
DROP TABLE IF EXISTS faceted_browse_page;
DROP TABLE IF EXISTS faceted_browse_page;
DROP TABLE IF EXISTS faceted_browse_category;
DROP TABLE IF EXISTS faceted_browse_facet;
DELETE FROM module WHERE id = 'FacetedBrowse';
```
